### ISSUE TITLE
python_asyncio example still relevant?

### ISSUE THREAD

**Issue by nickmachairas** [polygon-io/client-examples#17]
Hello, I notice that the python_asyncio example was last updated two years ago? Is it still relevant? I am looking for examples that will help me set up a messaging stream to Kafka or GCP Pub/Sub using Polygon's websocket. Thanks!

**Comment by justinpolygon** [comment]
Apologies for the late reply @nickmachairas. Is this still an issue? We suspect not given the time elapsed, but would like to assist if there's still a problem. Otherwise, we'll close the ticket in a week.

Just a heads up, we have the official Polygon.io Python client here: https://github.com/polygon-io/client-python
