### ISSUE TITLE
Python example 404s from website link

### ISSUE THREAD

**Issue by timkpaine** [polygon-io/client-examples#18]
<img width="442" alt="Screen Shot 2022-01-05 at 13 58 19" src="https://user-images.githubusercontent.com/3105306/148273417-ffe9763d-067a-4dcf-9b8f-b137b9ab1ece.png">

This is looking for this path: https://github.com/polygon-io/client-python/blob/master/websocket-example.py

**Comment by justinpolygon** [comment]
Apologies for the late reply @timkpaine. Thanks for reporting this. We've rolled out a new version of the website since this issue was reported and it appears fixed. So, I suspect this still isn't an issue right? We suspect not given the time elapsed, but would like to assist if there's still a problem. Otherwise, we'll close the ticket in a week.

You can access the latest client libraries and code examples via https://polygon.io/sample-applications.

**Comment by timkpaine** [comment]
Yep looks like it now correctly points to https://github.com/polygon-io/client-python/tree/master/polygon/websocket
