### ISSUE TITLE
is there any references for iOS?

### ISSUE THREAD

**Issue by HANBYEOL-YOO-developer** [polygon-io/client-examples#19]
I use WebSocket library as below.
https://github.com/socketio/socket.io-client-swift

and I want to use Polygon WebSocket services.

If I wanna emit below values what is the "auth key"?
{"action":"auth","params":"********"}

I should use emit only one key & value like this.
socket.emit("{auth key}", ["key": "value", "key", "value"])

**Comment by justinpolygon** [comment]
Apologies for the late reply @HANBYEOL-YOO-developer. Is this still an issue? We suspect not given the time elapsed, but would like to assist if there's still a problem. Otherwise, we'll close the ticket in a week.

To answer your question though the auth string would look like this: `{"action":"auth","params":"${APIKEY}"}`
